apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-07T16:09:47Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "46"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 475b6faa-57cc-41c8-af98-99fe65a14be0
  spec:
    clusterIP: 10.0.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-07T16:33:44Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    name: my-service
    namespace: default
    resourceVersion: "3445"
    selfLink: /api/v1/namespaces/default/services/my-service
    uid: 3635153a-4f9d-44e3-9dd1-6731cf363503
  spec:
    clusterIP: 10.0.71.229
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31014
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 51.124.92.75
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
